version: '3'
services:
  server:
    container_name: server
    restart: always
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/apache2:/var/log/apache2
    links:
      - db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpswd
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userDB
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d  
      - db_volume:/var/lib/mysql
    ports:
      - 9906:3306
  front:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - db
      - server
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5
volumes:
  db_volume:
